Unload models from RAM when it is unused
typesense/typesense pull request #1282
Opened 2023-10-07 12:09 UTC by ozanarmagan

## Change Summary

## PR Checklist

- [X] I have read and signed the [Contributor License Agreement](https://forms.gle/PZyiY5N2GDQU8GsV9).

2023-10-07 12:10 UTC, ozanarmagan commented
To fix #1266

2023-10-08 15:48 UTC, kishorenc requested changes

2023-10-08 15:48 UTC, kishorenc commented on src/collection.cpp
> +    if(embedding_fields.find(field_name) != embedding_fields.end()) {
You can do early return with `==` check so that `del_field` can be directly assigned after that.

2023-10-08 15:48 UTC, kishorenc commented on src/collection.cpp
> +    embedding_fields.erase(field_name);
Make sure that the caller of the method has appropriate locks.

2023-10-08 15:48 UTC, kishorenc commented on src/collection.cpp
> +        auto embedding_fields_other = collection->embedding_fields;
Must be `const auto &`

2023-10-08 15:48 UTC, kishorenc commented on src/collection_manager.cpp
> +                                                 req_json["fields"], fallback_field_type, fields, req_json["name"]);
`req_json["name"]` is redundant.

2023-10-08 15:48 UTC, kishorenc commented on src/field.cpp
> +                                          std::vector<field>& the_fields, const std::string& collection_name) {
`collection_name` is redundant.

2023-10-08 15:48 UTC, kishorenc commented on src/field.cpp
> +            auto validate_res = validate_and_init_embed_field(dummy_search_schema, field_json, fields_json, the_fields.back(), collection_name);
`collection_name` is redundant.

2023-10-08 15:48 UTC, kishorenc commented on src/field.cpp
> +                                                  field& the_field, const std::string& collection_name) {
`collection_name` is redundant.

2023-10-08 15:48 UTC, kishorenc commented on src/collection_manager.cpp
> +    for(auto& embedding_field : embedding_fields) {
This logic looks be duplicated in `remove_embedding_field`. Should consolidate into a function.

2023-10-08 15:48 UTC, kishorenc commented on src/collection_manager.cpp
> +    auto embedding_fields = collection->get_embedding_fields();
Should be before `s_lock.unlock()` if you want to copy the fields, or move it after `u_lock` below if you want to have reference. I recommend the second approach (reference).

2023-10-08 15:48 UTC, kishorenc commented on include/collection.h
> -    Option<bool> batch_alter_data(const std::vector<field>& alter_fields,
`const` should be put back.

2023-10-09 03:51 UTC, kishorenc requested changes

2023-10-09 03:51 UTC, kishorenc commented on src/collection.cpp
> +    auto del_field = embedding_fields[field_name];
`const auto &`

2023-10-09 03:51 UTC, kishorenc commented on src/collection.cpp
> +    auto model_name = del_field.embed[fields::model_config]["model_name"].get<std::string>();
`const auto &`

2023-10-09 03:51 UTC, kishorenc commented on src/collection.cpp
> +        auto embedding_fields_other = collection->embedding_fields;
`const auto &`

2023-10-09 03:51 UTC, kishorenc commented on test/collection_vector_search_test.cpp
> +TEST_F(CollectionVectorTest, TestUnloadingModelsOnDrop) {
Can we add another test where the dropped collection has 2 embedding fields? In the past we have had issues where test covered only the single case.

2023-10-09 03:51 UTC, kishorenc commented on src/collection.cpp
> +                TextEmbedderManager::get_instance().validate_and_init_model(f.embed[fields::model_config], dummy_num_dim);
The result of the validation step is not being verified.

2023-10-09 03:51 UTC, kishorenc commented on src/collection.cpp
> +                auto model_config = embedding_field.embed[fields::model_config];
`const auto &`

2023-10-09 03:51 UTC, kishorenc commented on src/collection_manager.cpp
> +        auto model_name = embedding_field.embed[fields::model_config]["model_name"].get<std::string>();
`const auto &`

2023-10-09 03:57 UTC, kishorenc commented on src/collection_manager.cpp
> +    const auto& embedding_fields = collection->get_embedding_fields();
We still need a lock on this because we don't want another operation to modify embedding fields before we are done looping through it.

2023-10-09 13:40 UTC, merged