Sort by vector query
typesense/typesense pull request #1301
Opened 2023-10-13 23:08 UTC by ozanarmagan

## Change Summary

## PR Checklist

- [X] I have read and signed the [Contributor License Agreement](https://forms.gle/PZyiY5N2GDQU8GsV9).

2023-10-13 23:09 UTC, ozanarmagan commented
#1268

2023-10-14 12:23 UTC, kishorenc requested changes

2023-10-14 12:23 UTC, kishorenc commented on src/collection.cpp
> +                if(sort_field_std.vector_query.values.empty() && embedding_fields.find(sort_field_std.vector_query.field_name) != embedding_fields.end()) {
What if field `field_name` is not found?

2023-10-14 12:23 UTC, kishorenc commented on src/index.cpp
> +                    hnsw_index_t::normalize_vector(sort_fields[0].vector_query.values, normalized_values);
We should do this normalization in pre-processing. Otherwise we are doing this for every item found.

2023-10-14 12:23 UTC, kishorenc commented on src/index.cpp
> +                auto& field_vector_index = vector_index.at(sort_fields[0].vector_query.field_name);
Should avoid this lookup here. Let's store `field_vector_index` as part of sort_fields by wrapping vector_query by another struct.

2023-10-14 12:23 UTC, kishorenc commented on src/vector_query_ops.cpp
> +                if(vector_query.values.empty() && !allow_empty_query) {
When do we need `allow_empty_query`?

2023-10-16 05:14 UTC, kishorenc approved these changes

2023-10-16 05:14 UTC, merged