Add support for image embeddings using CLIP
typesense/typesense pull request #1385
Opened 2023-11-16 21:04 UTC by ozanarmagan

## Change Summary

## PR Checklist

- [X] I have read and signed the [Contributor License Agreement](https://forms.gle/PZyiY5N2GDQU8GsV9).

2023-11-16 21:57 UTC, ozanarmagan commented
#1073 & #1315

2023-11-17 15:56 UTC, kishorenc requested changes

2023-11-17 15:56 UTC, kishorenc commented on src/collection.cpp
> +                for(auto& field: fields) {
Instead of looping here, let's see if we can do this processing inside `validate_index_in_memory` which is already looping on the schema fields.

2023-11-23 14:54 UTC, kishorenc approved these changes

2023-11-23 14:54 UTC, merged