Add support for stop words
typesense/typesense pull request #755
Opened 2022-10-14 19:32 UTC by jasonbosco

Related to #248

2022-10-17 11:08 UTC, kishorenc requested changes
a) Do we need to also ignore stop words during indexing? This will help in saving memory but offers less flexibility during querying.
b) Stop word index must be de-coupled from collection and be a separate top level resource that's attached to a collection.

2022-10-17 11:08 UTC, kishorenc commented on include/stop_word_index.h
> +    static constexpr const char* COLLECTION_stop_word_PREFIX = "$CY";
Should be `COLLECTION_STOP_WORD_PREFIX`

2023-04-06 19:28 UTC, A4TIF commented
Any progress on this? Would love to have this feature. Thanks

2023-08-16 06:00 UTC, closed without merging

2023-09-25 13:52 UTC, jhwheeler commented
@kishorenc What is the status of the stop words feature? Looks like it was merged, but I can't find any docs.

2023-09-25 14:32 UTC, kishorenc commented
This has been merged to our current development branch and is available in `0.26.0.rc20`. Usage: https://gist.github.com/kishorenc/05593984e318e0ef5fcb80c300e7c9cf

2023-09-25 15:04 UTC, jhwheeler commented
Great news, thank you for the update! Looking forward to this 🚀

2024-01-25 15:10 UTC, zehawki commented
This is great, Ive been waiting for this for a long time. Notwithstanding https://typesense.org/docs/guide/migrating-from-algolia.html#key-features-in-algolia-not-in-typesense, "Server-side stop-words (can be implemented [client-side ](https://github.com/typesense/showcase-books-search/blob/b0b15dc88179566f85db21d2455c2d6c68668d5a/src/app.js#L186-L194))"

Would the stop words be configurable in this case?